package com.lzw.mapper;

import com.lzw.mapper.City;
import java.util.List;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    City selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    int updateByPrimaryKey(City record);
    
    List<City> selectByCity(City city);
}