package com.lzw.mapper;

public class Country {
	public Country(String name,String code)
	{
		setCountryname(name);
		setCountrycode(code);
	}
	
	Country()
	{
		
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Id
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.countryname
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    private String countryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.countrycode
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    private String countrycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Id
     *
     * @return the value of country.Id
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Id
     *
     * @param id the value for country.Id
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.countryname
     *
     * @return the value of country.countryname
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public String getCountryname() {
        return countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.countryname
     *
     * @param countryname the value for country.countryname
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public void setCountryname(String countryname) {
        this.countryname = countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.countrycode
     *
     * @return the value of country.countrycode
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.countrycode
     *
     * @param countrycode the value for country.countrycode
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }
}