package com.lzw.mapper;

public class Provinces {
	
	public Provinces(String name,String code,String fatherNode)
	{
		setProvincename(name);
		setProvincecode(code);
		setFathernode(fatherNode);
	}
	Provinces()
	{
		
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.Id
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.provincename
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.provincecode
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    private String provincecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provinces.fathernode
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    private String fathernode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.Id
     *
     * @return the value of provinces.Id
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.Id
     *
     * @param id the value for provinces.Id
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.provincename
     *
     * @return the value of provinces.provincename
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.provincename
     *
     * @param provincename the value for provinces.provincename
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.provincecode
     *
     * @return the value of provinces.provincecode
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public String getProvincecode() {
        return provincecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.provincecode
     *
     * @param provincecode the value for provinces.provincecode
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public void setProvincecode(String provincecode) {
        this.provincecode = provincecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provinces.fathernode
     *
     * @return the value of provinces.fathernode
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public String getFathernode() {
        return fathernode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provinces.fathernode
     *
     * @param fathernode the value for provinces.fathernode
     *
     * @mbggenerated Mon May 15 10:54:14 GMT+08:00 2017
     */
    public void setFathernode(String fathernode) {
        this.fathernode = fathernode;
    }
}